### ISSUE TITLE
Overriding values is broken

### ISSUE THREAD

**Issue by rglopeza** [wojole/pytest-testconfig#1]
Within pytest configure there's an attempt to create/edit keys in what should be the global config dict, but since config is being taken in by pytest_configure, it ends up being the pytest Config object which does not allow dict like overrides.

Suggestion, rename global config var to not conflict with pytests' Config object used in pytest_configure.

**Comment by wojole** [comment]
fixed by commit https://github.com/wojole/pytest-testconfig/commit/82eadeb2a287ca981a75a09114c4bf49236b7ac1
