### ISSUE TITLE
what is the default file name and file path of the configuration?

### ISSUE THREAD

**Issue by andreabisello** [wojole/pytest-testconfig#7]
i'm able to use pytest-testconfig only passing --tc-file parameter,
because without this parameter i'm not able to understand what should to be the default file  (and path) of the configuration file.

**Comment by andreaschiffo** [comment]
AFAIK there's no default file so if you want to use a config file that's the way.

**Comment by andreabisello** [comment]
understand.

so i modified my pycharm configuration to run pytest with the default config

![image](https://user-images.githubusercontent.com/2149815/69065472-1f627980-0a20-11ea-8a64-14c0883bd132.png)

**Comment by bskrobek** [comment]
@andreaschiffo you are right. 

There is no default pytest-testconfig file. To use this plugin you have to add --tc-file parameter with path to file 

@andreabisello
Optional
You can create pytest.ini file and add to them --tc-file parameter with path

**Comment by andreabisello** [comment]
@bskrobek  sorry i neved saw this answer.
i really like adding --tc-file parameter on pytest.ini ! 
i use for the default environment

**Comment by andreabisello** [comment]
@bskrobek if i need to overwrite the addopts parameters defined in pytest.ini by command line, should i use the -o syntax as described [here](https://docs.pytest.org/en/3.4.2/customize.html#builtin-configuration-file-options) ?  
so now my pytest.ini file is

```
[pytest]
python_files = test_*
python_classes = Test*
python_functions = test_*
addopts = --tc-file=configurations/utenze/andrea-integration.ini --tc-file=configurations/puntamenti/integration.ini
```

if i need to overwrite the addopts should i try

`pytest --tc-file=configurations/utenze/something-else.ini --tc-file=configurations/puntamenti/something-ese.ini`

or

`pytest -o --tc-file=configurations/utenze/something-ese.ini -o --tc-file=configurations/puntamenti/something-else.ini`

?

i'm not able to understand with documentation (i will make a pull request) and i'm not sure of results i'm obtaining.

thanks.

**Comment by bskrobek** [comment]
@andreabisello I can't check overwrite for now, maybe later this day

But maybe this solution is good for you:

You can create few pytest.ini fles. For example:

**pytest.ini - with default configuration**

`[pytest]
python_files = test_*
python_classes = Test*
python_functions = test_*
addopts = --tc-file=configurations/utenze/andrea-integration.ini --tc-file=configurations/puntamenti/integration.ini`

and 

**pytest-dev.ini - with configuration for dev environment** 

`[pytest]
python_files = test_*
python_classes = Test*
python_functions = test_*
addopts = --tc-file=configurations/utenze/something-else.ini --tc-file=configurations/utenze/something-else-else.ini`

If you want to run tests with default configuration you type just `pytest` and pytest.ini will be loaded but if you wan to run tests with `pytest-dev.ini` file you can type `pytest -c pytest-dev.ini`


I don't know that this is helpful for you because this solution is very similar to pytest-testconfig usage but command can be shorter.

**Comment by andreabisello** [comment]
@bskrobek interesting.
thanks.
anyway i made some tries and it looks like the command line can override pytest.ini addopts without needs to use -o parameter.

**Comment by andreabisello** [comment]
@bskrobek oh no, it read all the parameters, it looks  working only because the cli arguments works after the ini parameters.
i will try with the -c parameter, storing default configuration inside pytest.ini and using command line to select a new configuration

**Comment by andreabisello** [comment]
@bskrobek 

i think there are differences between 

-c
-tc

because with -c is pytest that load the configuration file,
with -tc is pytest-testconfig that load the configuration file, but also pytest loads the configuration file, so you got the pytest configuration file + pytest-testconfig configuration file

-c command works good for me.

now i'm able to write a test result file name considering the parametrization loaded :

```
# @pytest.hookimpl(tryfirst=True)
def pytest_configure(config):

    if not os.path.exists('reports'):
        os.makedirs('reports')

    file_name = datetime.now().strftime("%d-%m-%Y %H-%M-%S") + ".html"

    moduli = config.option.file_or_dir

    if moduli is not None:
        for modulo in moduli:
            print("modulo -> " + modulo)
            if modulo is not None and ".py" in modulo:
                nome_modulo = modulo.split("/").pop()[:-3]
                file_name = nome_modulo+"_"+file_name

    parameters = config.option.testconfig

    if parameters is not None:
        for param in parameters:
            if param is not None:
                print("parametro -> " + param)
            if param is not None and ".ini" in param:
                configurazione = param.split("/").pop()[:-4]
                file_name = configurazione+"_"+file_name

    config.option.htmlpath = 'reports/' + file_name

```

**Comment by bskrobek** [comment]
@andreabisello

Of course there are differences in this parameters, I mentioned only that this solution is very similar but as you said we have two configuration files: pytest configuration file + pytest-testconfig configuration file ;)

I'm happy that your problem is solved
