### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by andreabisello** [wojole/pytest-testconfig#8]
clone
https://github.com/andreabisello/test-config-temptative
run
pytest --tc-file=config.ini
if in conftest.py you put
```
import lib
```
you obtain
```
ImportError while loading conftest 'C:\src\test-config-temptative\conftest.py'.
conftest.py:1: in <module>
    import lib
lib.py:3: in <module>
    valore = config['something']['a_value']
E   KeyError: 'something'
```

else,not.

but the key **config['something']['a_value']**  is defined,
due **test_something_with_import.py** use it, and it works.

it looks like conftest runs before pytest_testconfig load the configuration.

**Comment by andreabisello** [comment]
i created this https://github.com/andreabisello/test-config-temptative
it seems to work.
there should to be something wrong with my main project.
sorry.
i will check again and share the error.

**Comment by andreaschiffo** [comment]
Hey. Yes, as per the example it seems fine. Check the imports on your main project.

**Comment by andreabisello** [comment]
@andreaschiffo thanks for your help. 
maybe there can be something wrong due the use of the singleton and the conftest.py file used by pytest? 

i'm not able to reproduce the problem in the example problem, but i'm not able to use the plugin in a complex project.

at the beginning, i put all the configuration in a configuration.py file.

now i'm moving on a ini file.

so i started moving all parameters on a configuration.ini file and every test read the config from pytest_testconfig.

everything goes well with the xxx_test.py files.

now i need to move also utils.py , a file that contains utils methods , from a configuration based on the configuration.py file, to the config.ini file.

i created a utils_2c.py file, in order to switch from utils.py (don't worry about the meaning of 2c).

![image](https://user-images.githubusercontent.com/2149815/69131381-9ba59d00-0ab2-11ea-977e-3458ed985d9d.png)

as you can see in the bottom part, i read data from config.

it works.

the test import utils from the file and everything works.

![image](https://user-images.githubusercontent.com/2149815/69131606-f3440880-0ab2-11ea-89ef-cb090c1578ce.png)

now i make the same thing on another test file

![image](https://user-images.githubusercontent.com/2149815/69131926-5afa5380-0ab3-11ea-85cb-0135d3f90bd6.png)

but the exception is raised from conftest.py, 

and conftest is not using testconfig

![image](https://user-images.githubusercontent.com/2149815/69131985-7e250300-0ab3-11ea-8d3c-a1e84f8fa02c.png)

i'm stuck.

any suggestion?

thanks.

**Comment by andreaschiffo** [comment]
I suspect you need to add your project base dir to the Pythonpath, before running the tests.
Could you try and let me know if it works?

Also, I don't see file_to_bytes being defined in the utils_2c.py file. Is it defined somewhere else (I imagine in susd.wsse)? If yes I'd say it would be good to import it directly from there rather than import everything in the config then import that from the config.

**Comment by andreaschiffo** [comment]
Or it may be that the lib is loaded by Python before the config is, hence the lib is unaware of the config.

**Comment by andreabisello** [comment]
utils_2c is a clone of  utils , the difference is utils read configuration from configuration.py and utils_2c read configuration from config.ini file using pytest-testconfig.

file_to_bytes is contained in the utils lib.

the configuration file contains only variables , like username and password.

i added PYTHONPATH to system variables, i reloaded pycharm, nothing changed.

conftest is the first file pytest load ,

and conftest ask for  lib.utils_2c with

```
from lib.utils_2c import file_to_bytes
```
but is the same library and the same conftest.py used by the other test file that works.

**Comment by andreabisello** [comment]
@andreaschiffo i understand how to reproduce the issue.
if you pull the project,
you will see i added a very simple conftest.py file.
in the conftest.py file there

```
from lib.utils import file_to_bytes
```

with this file , running "test_something.py" you will obtain

```
ImportError while loading conftest 'C:\src\test-config-temptative\conftest.py'.
conftest.py:1: in <module>
    from lib.utils import file_to_bytes
lib.py:3: in <module>
    valore = config['something']['a_value']
E   KeyError: 'something'
```
from conftest.
if you comment the import,
the test will work.

are you able to understand why?

thanks.

**Comment by andreabisello** [comment]
@andreaschiffo i removed all the previous comment,
and started a new thread again.
i was able to reproduce the issue.

**Comment by andreabisello** [comment]
@andreaschiffo  hi Andrea.
have you tried my repository ? 
thanks.

**Comment by lucrib** [comment]
This issue seems related to what I am trying to solve with PR #10

**Comment by andreabisello** [comment]
@lucrib i think you are right. thanks for your PR

**Comment by bskrobek** [comment]
@andreabisello is your problem solved?

**Comment by andreabisello** [comment]
@bskrobek i will try in the afternoon, thanks

**Comment by andreabisello** [comment]
now it works,
thanks!

**Comment by andreabisello** [comment]
@bskrobek @lucrib 

sorry if i'm returning on this issue.

When i closed this issue, i thought  pytest-testconfig was loaded before conftest.py thanks to the pr of @lucrib because the use case was solved : it looks like the configuration was loaded before conftest runs.

but now, i'm not sure again,

because if you clone my repository

https://github.com/andreabisello/test-config-temptative

and you run test_something in test_something.py you obtain the same problem

```
ImportError while loading conftest 'C:\src\test-config-temptative\conftest.py'.
conftest.py:1: in <module>
    from lib import do_something
lib.py:3: in <module>
    valore = config['something']['a_value']
E   KeyError: 'something'
```

due because conftest import "lib" and "lib" use a value from test-config

```
from pytest_testconfig import config
valore = config['something']['a_value']
```

i'm making something wrong? maybe the problem was introducted again after i moved to latest versions of pytest ? 

thanks for your help again.

**Comment by aleksandr-kotlyar** [comment]
@andreabisello 

Hello, i saw your problem https://github.com/wojole/pytest-testconfig/issues/8#issuecomment-603870018 and i think i found the cause in your code: 
> The problem was with constant initialization 'valore' which was not in 'test_' files. Seems that config parser cant be defined as a constant not in test modules.

Look full description in my PR with fix: https://github.com/andreabisello/test-config-temptative/pull/1
Hope it solves your last question.

Have a good day!

**Comment by andreabisello** [comment]
Thanks i Will try asap

Il Dom 15 Nov 2020, 11:57 Aleksandr Kotlyar <notifications@github.com> ha
scritto:

**Comment by andreabisello** [comment]
@aleksandr-kotlyar with modifications you proposed, it works! thanks
